2 страницы
htmlacademy-htmlcss/2248995-device-36 pull request #2
Opened 2023-01-20 17:51 UTC by Serega560

2023-01-21 09:21 UTC, Kartaviy-arteom requested changes

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +      <a href="index.html"><img src="#" alt="Логотип Магазина Девайс" class="logo logo-header"></a>
тебе нужно соблюдать форматирование документа для соблюдения требований академии и удобочитаемости документа. Касается и главной страницы
В vscode есть автоформат, частично поможет исправить
On Windows Shift + Alt + F
On Mac Shift + Option + F
On Linux Ctrl + Shift + I

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +  <nav class="navigation">
в nav лучше вынести основные ссылки: каталог и тд

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +      <li class="navigation-item"><button type="serch">Найти</button></li>
это форма. input с label + кнопка type submit

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +      <img src="" alt="Иконка человека">
декоративная графика в разметке не нужна

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +      <img src="" alt="Иконка сравнения">
img не нужна

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +      <img src="" alt="Иконка Корзины">
img не нужна

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +<p><a href="#">КАТАЛОГ ТОВАРОВ</a></p>
параграф тут не нужен

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +<button type="button"></button>
у кнопки должен быть тип и описание

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +</ul>
лишний закрывающий тег

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +<header class="header-inner">
тебе не нужен тут еще один хедер

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +    <h1 class="visiually-hidden">Магазин "Девайс"
основной заголовок тут будет "Моноподы для селфи". На странице должен быть один  заголовок h1

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +<ul class="breadcrumbs-list">
лучше ol

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +  <li class="breadcrumbs-item"><a class="breadcrumbs-link" href="index.html"></a>Главная</li>
текст вне ссылки

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +</ul>
невалидная разметка

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +<section>
правильнее будет выделить секцию каталога, а внутри нее выделитьЖ фильтры, сортировку, список товаров и пагинацию

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +<fieldset class="catalog-filter-group">
это внутри формы

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +  <Ul class="catolog-filter-list">
теги с маленькой буквы все, это критерий написания кода, так разметка нерегистрозависима

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +</Ul>
чекбоксы нужно сгрупировать по имени, но у них будет уникальный value, так же тут разметка получается невалидна из-за незакрытых ранее тегов

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> + <button type="button">Показать</button>
тип кнопке. Форма должна закончиться здесь

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +  <option value="">Популярные</option>
тут заголовок тогда будет h3, сортировка просто select, внутри option

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +</a>
это кнопки сортировки по убыванию, по возрастанию

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +      <h3 class="product-card-title">Любительская селфи-палка</h3>
вероятно уровень изменится, будет видно когда выше исправишь

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +        <a href="">Загрузить еще</a>
кнопка загрузки, перехода не будет

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +</header>
тут закончился main

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +    <img src="" alt="Магазин Девайс" class="footer-contacts-logo">
это ссылка на главную

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +        <a href="#" class="contacts-phone" >Тел.: +7 (812) 812-12-12</a>
в href будет tel

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +    <img src="№" alt="Желтая палочка">
img не нужна

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +    <a href=""><img src="#" alt="Теллеграмм"></a>
список соцсетей, без img

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +        <img src="slider-1.png" alt="Логотип Магазина Девайс" class="logo logo-header">
можно оставить ссылку, но без href. Упростит переиспользование, далее аналогично каталогу

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +    <p><a href="#">Подробнее</a></p>
абзац не нужен

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +    <button type="button" class="visiually-hidden">Кнопка назад</button>
тут будет секция со слайдером, состоящая из 3-х слайдов

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +    <button type="button" class="visiually-hidden">Кнопка вперед</button>
это кнопка смены фото, ей не нужен этот класс

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +    <p>Радиус поражения</p>
лучше теги dl, dt,dd

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +<section class="gadjets">
заголовок для секции

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +    <li class="navigation-item"><img src="#" alt="Очки для Виртуальной реальности"> Виртуальная реальность</li>
лучше картинки в декоративную графику

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +<section>
заголовок секции

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +    <li class="navigation-item"><a href="" class="navigation-link">Кредит</a></li>
это кнопки, которые переключают содержимое справа

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +  <img src="" alt="Черная палочка-перегородка">
img не нужен

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +<p>Доставка</p>
нужно подобрать другой тег

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +  <img src="#" alt="Человек-доставщик">
не нужно в разметке

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +  </section>
лишние img, это все одна кнопка для показа модалки, не нужно выносить ее в отделбную секцию

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +    <p><a href="#">Подробнее о нас</a></p>
параграф не нужен

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +      <p>+7 (812) 812-12-12</p>
ссылка

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +        <p><a href="#">Напишите нам</a></p>
параграф не нужен

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +      <p>Это бесплатно</p>
это форма, img не нужен

2023-01-21 09:21 UTC, Kartaviy-arteom commented on index.html
> +<footer class="page-footer">
футер аналогично каталогу

2023-01-21 09:21 UTC, Kartaviy-arteom commented on style.css
> +.page-header{
будут в дирректории styles

2023-01-21 09:21 UTC, Kartaviy-arteom commented on style.css
> +}
необходимо соблюдать форматирование

2023-01-21 09:21 UTC, Kartaviy-arteom commented on catalog.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
этот тег тут не обязателен, в первом курсе нет адаптивов

2023-01-21 10:46 UTC, Serega560 commented on catalog.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
понял, я просто с помощью !+Tab делаю эту начинку, там metы уже сразу вписаны

2023-01-21 11:45 UTC, Serega560 commented on catalog.html
> +      <img src="" alt="Иконка сравнения">
убрал

2023-01-21 11:46 UTC, Serega560 commented on catalog.html
> +      <img src="" alt="Иконка человека">
убрал

2023-01-21 12:04 UTC, Serega560 commented on style.css
> +.page-header{
ок, это так, попробовал

2023-01-21 12:04 UTC, Serega560 commented on style.css
> +}
да, понял, это просто проба была

2023-01-21 17:08 UTC, Serega560 commented on catalog.html
> +      <li class="navigation-item"><button type="serch">Найти</button></li>
Обернул в форму

2023-01-21 17:09 UTC, Serega560 commented on index.html
> +      <p>Это бесплатно</p>
Обернул в форму , img удалил

2023-01-21 17:10 UTC, Serega560 commented on catalog.html
> +      <a href="index.html"><img src="#" alt="Логотип Магазина Девайс" class="logo logo-header"></a>
Исправил и одну и другую страницы

2023-01-21 17:11 UTC, Serega560 commented on catalog.html
> +  <nav class="navigation">
вынес каталог, доставка, гарантия, контакты

2023-01-21 17:14 UTC, Serega560 commented on index.html
> +<footer class="page-footer">
Здесь не понял
у меня на двух страницах footer одинаковый. я с index.html  скопировал в catalog.html

2023-01-24 14:15 UTC, Kartaviy-arteom requested changes

2023-01-24 14:15 UTC, Kartaviy-arteom commented on catalog.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
этот тег на первом курсе, не нужен, но это и не ошибка

2023-01-24 14:15 UTC, Kartaviy-arteom commented on catalog.html
> +    <link rel="stylesheet" href="style.css">
все стили будут храниться в дирректории styles, не в корне проекта

2023-01-24 14:15 UTC, Kartaviy-arteom commented on catalog.html
> +          <button class="dropdown" type="button">Кнопка</button>
это все один элемент. тут не нужно два отдельных элемента

2023-01-24 14:15 UTC, Kartaviy-arteom commented on catalog.html
> +                  <input type="checkbox" name="black" checked>Черный
label должен быть связан с input и далее. Чекбоксы нужно связать между собой через name

2023-01-24 14:15 UTC, Kartaviy-arteom commented on catalog.html
> +          <button class="link" type="button" >Показать</button>
кнопка внутри формы

2023-01-24 14:15 UTC, Kartaviy-arteom commented on catalog.html
> +            <a href="#" class="product-card-link">
ссылкой все содержимое карточки лучше тогда

2023-01-24 14:15 UTC, Kartaviy-arteom commented on catalog.html
> +          <a href="">Загрузить еще</a>
это кнопка

2023-01-24 14:15 UTC, Kartaviy-arteom commented on catalog.html
> +          <a class="contacts-phone" href="#" >Тел.: +7 (812) 812-12-12</a>
телефон не в этой части футера

2023-01-24 14:15 UTC, Kartaviy-arteom commented on index.html
> +        <span class="visiually-hidden">Кнопка вперед</span>
лучше написать что она делает, то что это кнопка это понятно.

2023-01-24 14:15 UTC, Kartaviy-arteom commented on index.html
> +      <button type="button">
из этого нужно собрать секцию в которой будет слайдер

2023-01-24 14:15 UTC, Kartaviy-arteom commented on index.html
> +            <img src="#" alt="Очки для Виртуальной реальности"> Виртуальная реальность
это обернуть нужно в ссылки

2023-01-24 14:15 UTC, Kartaviy-arteom commented on index.html
> +            <a class="navigation-link link" href="#">Доставка</a>
тут будут кнопки

2023-01-24 14:15 UTC, Kartaviy-arteom commented on index.html
> +        <p>Доставим редкий товар под заказ</p>
это кнопка для модалки

2023-01-24 14:15 UTC, Kartaviy-arteom commented on index.html
> +        <button type="button">Подписаться</button>
тип у кнопки

2023-01-24 14:15 UTC, Kartaviy-arteom commented on index.html
> +        <p>Это бесплатно</p>
лучше не p

2023-01-24 14:15 UTC, Kartaviy-arteom commented on index.html
> +          <a class="contacts-phone" href="#" >Тел.: +7 (812) 812-12-12</a>
в href ссылка на телефон

2023-01-24 14:15 UTC, Kartaviy-arteom commented on index.html
> +          <img src="#" alt="Теллеграмм">
img эти не нужны

2023-01-24 14:15 UTC, Kartaviy-arteom commented on style.css
> +}
форматирование

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +        <label for="search"></label>
пояснение

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +      <ul class="navigation-list">
перед nav

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +        <button class="dropdown" type="button">Каталог товаров</button>
ссылка

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +        <h2 class="filter">Фильтр</h2>
каталог с фильтрами

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +        <h3 class="catalog-filter-title">Стоимость</h3>
будет легендой внутри fieldset

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +        <input class="max" type="range" min="0" max="10000" step="100"/>
внутри формы

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +                  <input type="checkbox" name="color" value="white" id="color-white" checked/>Белый
форматирование

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +        <h2 class="filter">Сортировка</h2>
результаты поиска

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +        <option>Популярные</option>
select

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +        <span class="visually-hidden">Вверх</span>
кнопки

2023-01-29 12:04 UTC, Kartaviy-arteom commented on catalog.html
> +          <b class="product-card-price">500 P</b>
цену внутрь ссылки

2023-01-29 12:04 UTC, Kartaviy-arteom commented on index.html
> +      <img src="images/header/01.svg" width="250" height="135" alt="цифры 01" style="background-color: rgb(222, 237, 18)"/>
не нужно

2023-01-29 12:04 UTC, Kartaviy-arteom commented on index.html
> +      <img src="images/main/png/Квадрокоптер.png" width="560" height="560" alt="Квадрокоптер"/>
левая половина изображение и две кнопки

2023-01-29 12:04 UTC, Kartaviy-arteom commented on index.html
> +        <form action="post">
метод, post - это метод

2023-02-01 18:26 UTC, Kartaviy-arteom approved these changes

2023-02-01 18:26 UTC, Kartaviy-arteom commented on styles/styles.css
> +}
в конце правила будем ставить везде ;
`background-color: #FFE17F;`

2023-02-01 18:27 UTC, merged